### ISSUE TITLE
Добавить компонент swipe

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/gdmn-webservice#100]
Я его уже подключил в 1 проект так что перед началом лучше посмотреть там

**Comment by stasgm** [comment]
https://github.com/stasgm/expo-ui-test1/blob/c989d5bea97674f35edffd3abb10f4eb6f5d1475/src/screens/World/List.tsx#L79

**Comment by stasgm** [comment]
@sunnycreature закрой issue и добавь ссылку на коммит

**Comment by sunnycreature** [comment]
https://github.com/gsbelarus/gdmn-webservice/commit/aa899d6435c5f3c09bbfdb8e82f3818ffdcf3137#diff-6811e32788e42135131d2e66a2be2ea5ce9525ad35fca7c2a3c629f6d7d0928a
