### ISSUE TITLE
Доработки и исправления по отвесам

### ISSUE THREAD

**Issue by ilonaand** [gsbelarus/gdmn-webservice#105]
- [x] 1. Проверить фильтрацию. Надо, чтобы работало и по номеру, и по экспедитору, и по организации
- [x] 2. При изменении шапки слетают все параметры, но периодически. Проверить.
- [x] 3. Итоги по количеству и по количеству по заявке
- [x] 4. Заменить календарь в параметрах- этот часто глючит
- [x] 5. В настройках в выпадающем меню Удалить все данные поставить первым по списку и желательно еще и отделить пустым пунктом, трудно попадать в перчатках

**Comment by stasgm** [comment]
>>1. Проверить фильтрацию. Надо, чтобы работало и по номеру, и по экспедитору, и по организации
@ilonaand а подразделение?

**Comment by ilonaand** [comment]
тоже, но там оно одно

**Comment by stasgm** [comment]
@ilonaand проверяй если всё ок, закрывай
