### ISSUE TITLE
Новые вопросы по отвесам 

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/gdmn-webservice#112]
- [x] Проблема со сменой пользователя 
- [x] Ввод количества, не даёт указать 0
- [x] не дает указать дробное количество

**Comment by ilonaand** [comment]
Не дает указать дробное количество

**Comment by stasgm** [comment]
@ilonaand проблемы со сменой пользователя не обнаружил.

**Comment by ilonaand** [comment]
Я тоже, у Жени после перегрузки тоже исчезла. Будем считать, глюк)

**Comment by stasgm** [comment]
@ilonaand проверяй завтра.

**Comment by stasgm** [comment]
@ilonaand закрываю
