### ISSUE TITLE
Изменение пользователя в веб-интерфейсах

### ISSUE THREAD

**Issue by LenaBuraja** [gsbelarus/gdmn-webservice#44]
Быают ситуации, когда удаляются все организации при изменении или добавляются поля, которые не связаны с интерфейсом пользователя. Часто возникает после создания нового пользователя -> добавление его в организации -> изменения его -> переход на администратора -> изменение его.

**Comment by stasgm** [comment]
Сначала выполнить эту задачу https://github.com/gsbelarus/gdmn-webservice/issues/98

**Comment by LenaBuraja** [comment]
5dfe2ba
