### ISSUE TITLE
Использование компонента BottomSheets для выбора параметров при создании документа

### ISSUE THREAD

**Issue by stasgm** [gsbelarus/gdmn-webservice#94]
Заменить выбор параметров в проекте Inventory

**Comment by sunnycreature** [comment]
https://github.com/gsbelarus/gdmn-webservice/commit/cd575252bcd5ece497880f3e49bd9ee4219799a6

**Comment by sunnycreature** [comment]
https://github.com/gsbelarus/gdmn-webservice/commit/a9504800462cf229a712b3747e2bcb8cd36905ed#diff-b0792671a631bf4216b4458f8caa46a93bc03897a54d450a5b90fc23147e5621
