### ISSUE TITLE
Навигация в мобильном

### ISSUE THREAD

**Issue by sunnycreature** [gsbelarus/gdmn-webservice#97]
При добавлении или редактировании документа, чтобы главное меню было не доступно.

**Comment by stasgm** [comment]
Скорее не недоступно, а чтобы дочерние экраны были на весь экран

**Comment by sunnycreature** [comment]
да, я это и имела в виду

**Comment by sunnycreature** [comment]
https://github.com/gsbelarus/gdmn-webservice/commit/9c0e22e9e917ae3525202754658db2bc5fee0df4#diff-f30ae3e5960176241cefce6876d6c699bd63ab85d28851e7cace82b97774a92e
